url: 'https://narayanshivansh49.github.io'
github_username: narayanshivansh49
baseurl: ''
lang: en
title: Shivansh Narayan
description: |
  Online Portfolio of Shivansh Narayan
tagline: |
  Pre final year I.T Student at BIT Mesra
keywords:
  - BIT
  - Mesra
  - I.T
logo: >-
  https://avatars3.githubusercontent.com/u/34347884?s=400&u=5ae91062f6c80ee7d43ff0047d8a692f6a457bd0&v=4
author:
  name: Shivansh Narayan
  email: narayanshivansh49@gmail.com
menu:
  - title: About
    url: /about/
  - title: Education
    url: /education/
  - title: Projects
    url: /projects/
  - title: Experience
    url: /exp/
  - title: Achievements
    url: /achievements/
permalink: '/:categories/:year-:month-:day-:title/'
paginate: 5
paginate_path: '/blog/page-:num/'
accent_image: /assets/img/35701506_1935132846517938_8952421413646499840_n3.jpg
accent_color: '#4fb1ba'
google_fonts: 'Roboto+Slab:400|Noto+Sans:400,400i,700,700i'
font: 'Noto Sans, Helvetica, Arial, sans-serif'
font_heading: 'Roboto Slab, Helvetica, Arial, sans-serif'
defaults:
  - scope:
      path: hyde
    values:
      accent_color: 'rgb(38,139,210)'
      accent_image:
        background: 'rgb(32,32,32)'
        overlay: false
  - scope:
      type: projects
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_categories
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_tags
    values:
      seo:
        type: WebPage
google_analytics: ''
disqus: photocyte-github-io
hydejack:
  post_addons: []
  project_addons: []
  no_google_fonts: false
  no_mark_external: true
  no_push_state: false
  no_drawer: false
  no_img: false
  no_inline_css: false
  no_page_style: false
  no_break_layout: false
  no_structured_data: false
  no_theme_color: false
  use_lsi: false
  cookies_banner: false
  advertise: false
  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true
  offline:
    enabled: false
    cache_version: 1
collections:
  featured_categories:
    permalink: '/:name/'
    output: true
  featured_tags:
    permalink: '/tag-:name/'
    output: true
  projects:
    permalink: '/projects/:path/'
    output: true
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - '*.gemspec'
  - _js
  - _plugins
  - .sass-cache
include:
  - LICENSE.md
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
social:
  name: Shivansh Narayan
  links:
    - 'https://github.com/narayanshivansh49'
    - 'https://www.linkedin.com/in/shivanshnarayan/'
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
  with_frontmatter: true
relative_links:
  collections: true
titles_from_headings:
  strip_title: true
  collections: true
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
compress_html:
  comments:
    - '<!-- '
    - ' -->'
  clippings: all
  endings: all
  ignore:
    envs:
      - development
sass:
  style: compressed
